# Site settings
title: Jessy Ayala
# general_email: your_general_email@gmail.com
# academic_email:
description: > # this means to ignore newlines until "baseurl:"
  Site built with Academic Portfolio, a Jekyll theme.
#
# baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://jayala-29.github.io" # the base hostname & protocol for your site

# github_username: jayala-29
twitter_username: MrAyala0
linkedin_username: jessy-ayala
instagram_username: 0o01232
# feel free to add other links here; you will have to add the SVG icon in _includes/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
