# Site settings
title: Yixin Zou (邹熠欣)
# general_email: your_general_email@gmail.com
academic_email: yixinz [at] umich [dot] edu

description: > # this means to ignore newlines until "baseurl:"
  Site modified from @ys1998.
#
# baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://yixinzou.github.io" # the base hostname & protocol for your site

twitter_username: yixinzou1124
linkedin_username: yixinzou
facebook_username: yixin1124
# feel free to add other links here; you will have to add the SVG icon in _includes/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
